POST localhost:8080/shorten
Content-Type: application/json

{
  "originalUrl": "https://example.com"
}

###

GET localhost:8080/kVOkZ

###

GET localhost:8080/stats/kVOkZ

###

GET localhost:8080/V0nV9

###

GET localhost:8080/stats/V0nV9

###

POST localhost:8080/shorten
Content-Type: application/json

{
  "originalUrl": "glorp"
}