{
 "title": "URL Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Response Time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri!~\"/actuator.*\"}[1m])) by (uri) / sum(rate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "system_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Old Gen\"} / on() group_left() sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Survivor Space\"} / on() group_left() sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "jvm_memory_used_bytes{id=\"G1 Eden Space\"} / on() group_left() sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "API Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1m])) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stored Shortened URLs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 14, "y": 11 },
   "targets": [
    { "expr": "shortened_urls", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{uri!~\"/actuator.*\",status=~\"5..\"}[1m])) / sum(rate(http_server_requests_seconds_count{uri!~\"/actuator.*\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max DB Command Completion Time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "lettuce_command_completion_seconds_max",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}